apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: nodeapp

images:
- name: nodeapp
  newName: blgianini/nodeapp
  newTag: 5be4b88de88f952d808b85ab5356985c51bc1007